build:image:
  script:
    - apk add --no-cache docker
    - python setup.py install
    - tutor config save
    - tutor images build discovery
  only:
    refs:
      - master
  tags:
    - private
  stage: build

deploy:image:
  script:
    - apk add --no-cache docker
    - python setup.py install
    - tutor config save
    - tutor images push discovery
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy

deploy:pypi:
  script:
    - apk add --no-cache make
    - pip3 install -U setuptools twine
    - python3 setup.py sdist
    - twine upload --skip-existing dist/tutor-discovery*.tar.gz
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy