build:image:
  script:
    - apk add --no-cache docker
    - python setup.py install
    - tutor plugins enable discovery
    - tutor config save
    - tutor images build discovery
  only:
    refs:
      - master
  tags:
    - private
  stage: build

deploy:image:
  script:
    - apk add --no-cache docker
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - python setup.py install
    - tutor plugins enable discovery
    - tutor config save
    - tutor images push discovery
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy

deploy:pypi:
  script:
    - apk add --no-cache make
    - pip3 install setuptools==41.6.0 twine==2.0.0
    - python3 setup.py sdist
    - twine upload --skip-existing dist/tutor-discovery*.tar.gz
  only:
    refs:
      - master
  tags:
    - private
  stage: deploy